# Importando Pacotes

In [1]:
import numpy as np
import pandas as pd

# Tipos de arrays

In [37]:
one_d = np.arange(6) # 1d array
one_d

array([0, 1, 2, 3, 4, 5])

In [38]:
two_d = np.arange(12).reshape(4, 3) # 2d array
two_d 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
three_d = np.arange(24).reshape(2, 3, 4)  # 3d array
three_d 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Preencher valores em um array

In [2]:
pares = np.array([n for n in range(0, 101, 2)])
pares

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [3]:
# Preencher valores de um array com 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# criar um array com 15 elementos iguais a 1
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# criar um array com 8 elementos iguais a 12
np.full(8,12)

array([12, 12, 12, 12, 12, 12, 12, 12])

In [6]:
# criar um array com 8 elementos iguais a 0, tipo inteiro
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# criar um array com 8 elementos iguais 1, tipo inteiro
np.ones(15, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
# criar um array com 8 elementos iguais a 12, tipo inteiro
np.full(8,12, dtype=int)

array([12, 12, 12, 12, 12, 12, 12, 12])

In [9]:
# criar um array bidimensional 2x5 preenchido com zeros, tipo inteiro.
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Criar arrays a partis de faixa de valores.

In [10]:
# Array de 10 elementos, números de 0 a 9.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Array de 10 elementos floats, de 0 a 9.
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
# Array com valores no intervalo de 5 a 15 valor 16 é exclusivo.
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
# Array com números de pares de 50 té 1
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [14]:
# Criar array com valores de ponto flutuante com o método linspace.
np.linspace(0.0,2.0, num=5)

array([0. , 0.5, 1. , 1.5, 2. ])

# Array com valores aleatórias - Métodos rand e randint

In [15]:
# Array de 10 elementos entre 0 e 1
np.random.rand(10)
np.random.rand(10)

array([0.43320014, 0.97395495, 0.77663305, 0.28148572, 0.95782138,
       0.87510726, 0.39813903, 0.5738845 , 0.05468808, 0.65949028])

In [16]:
# Array bidimensional 3x3 com valores aleatóris
np.random.rand(3,3)

array([[0.96375597, 0.25827498, 0.06190813],
       [0.02123226, 0.55983499, 0.35235327],
       [0.50034697, 0.13169835, 0.26055194]])

In [17]:
# Gerar um número aleatório inteiro entre 0 e 8 com random.randint
np.random.randint(9)


1

In [18]:
# Array unidimensional com 10 números aleatórios inteiros entre 10 e 20
np.random.randint(10,21,size=10)

array([19, 14, 20, 19, 13, 15, 15, 17, 17, 11])

In [19]:
# Array bidimensional 4x5 com números aleatórios inteiros entre 1 e 30
np.random.randint(1,31,size=(4,5))

array([[ 2, 30,  4, 25,  3],
       [18, 12, 16, 24, 22],
       [14,  2, 25,  5, 24],
       [30, 14, 10, 25, 25]])

In [27]:
array = np.random.randint(1,31,size=(5,5))
print(array)
df = pd.DataFrame(array)
df

[[18 24 20 25  4]
 [ 9 12 12 29  5]
 [12 30 29 26 16]
 [28 15 17 16 13]
 [19 16 25 23 18]]


0   1   2   3   4
0  18  24  20  25   4
1   9  12  12  29   5
2  12  30  29  26  16
3  28  15  17  16  13
4  19  16  25  23  18

In [28]:
array = np.random.randint(10,21,size=5)
print(array)
df = pd.DataFrame(array)
df

[15 18 16 14 14]


0
0  15
1  18
2  16
3  14
4  14

In [32]:
array = np.random.randint(10,21,size=(2,5))
print(array)
columns = ['A', 'B', 'C', 'D', 'E']
df = pd.DataFrame(array, columns=columns)
df

[[12 12 10 12 19]
 [15 12 13 10 12]]


A   B   C   D   E
0  12  12  10  12  19
1  15  12  13  10  12

In [33]:
df['A']

0    12
1    15
Name: A, dtype: int32

In [50]:
array = np.arange(1,10).reshape(3, 3)
print(array)
columns = ['A', 'B', 'C']
index = ['A', 'B', 'C']
df = pd.DataFrame(array, columns=columns, index=index)
df

[[1 2 3]
 [4 5 6]
 [7 8 9]]


A  B  C
A  1  2  3
B  4  5  6
C  7  8  9