In [4]:
import xarray as xr
import numpy as np
import pandas as pd

# Concatenate Data

In [5]:
da = xr.DataArray(
    np.arange(6).reshape(2, 3), [("x", ["a", "b"]), ("y", [10, 20, 30])]
)

da

<xarray.DataArray (x: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int32 10 20 30

In [6]:
da.isel(y=slice(0, 1))  # same as da[:, :1]

<xarray.DataArray (x: 2, y: 1)>
array([[0],
       [3]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int32 10

In [7]:
xr.concat([da[:, :1], da[:, 1:]], dim="y")

<xarray.DataArray (x: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

In [8]:
xr.concat([da.isel(y=slice(0, 1)), da.isel(y=slice(1, None))], dim="y")

<xarray.DataArray (x: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

In [9]:
da.sel(x="a")

<xarray.DataArray (y: 3)>
array([0, 1, 2])
Coordinates:
    x        <U1 'a'
  * y        (y) int32 10 20 30

In [10]:
xr.concat([da.isel(x=0), da.isel(x=1)], "x")

<xarray.DataArray (x: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int32 10 20 30

In [11]:
xr.concat([da.isel(x=0), da.isel(x=1)], "new_dim")

<xarray.DataArray (new_dim: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
    x        (new_dim) <U1 'a' 'b'
  * y        (y) int32 10 20 30
Dimensions without coordinates: new_dim

In [12]:
xr.concat([da.isel(x=0), da.isel(x=1)], pd.Index([-90, -100], name="new_dim"))

<xarray.DataArray (new_dim: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
    x        (new_dim) <U1 'a' 'b'
  * y        (y) int32 10 20 30
  * new_dim  (new_dim) int64 -90 -100

In [13]:
ds = da.to_dataset(name="foo")

xr.concat([ds.sel(x="a"), ds.sel(x="b")], "x")

<xarray.Dataset>
Dimensions:  (x: 2, y: 3)
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int32 10 20 30
Data variables:
    foo      (x, y) int32 0 1 2 3 4 5