In [1]:
# Importação dos Pacotes
import xarray as xr
import numpy as np

#### Creating an Xarray example

In [5]:
values = np.random.random(size=(4,3))
values


array([[0.57061223, 0.87339452, 0.9745001 ],
       [0.4613398 , 0.07907363, 0.48824393],
       [0.35956502, 0.89967718, 0.873587  ],
       [0.8278617 , 0.00243419, 0.30986971]])

In [6]:
# Dims Y represents rows and X represent columns.
dimensions = ("y", "x")

In [7]:
# Cordinates labels/values
cordinates = {
    "x":[10,11,12],
    "y":[10,20,30,40]
}

In [9]:
data = xr.DataArray(values, dims=dimensions, coords=cordinates )
data

<xarray.DataArray (y: 4, x: 3)>
array([[0.57061223, 0.87339452, 0.9745001 ],
       [0.4613398 , 0.07907363, 0.48824393],
       [0.35956502, 0.89967718, 0.873587  ],
       [0.8278617 , 0.00243419, 0.30986971]])
Coordinates:
  * x        (x) int32 10 11 12
  * y        (y) int32 10 20 30 40

### Coordinates and Attributes

#### Proprities of Xarray

In [11]:
data.dims

('y', 'x')

In [12]:
data.size

12

In [14]:
data.dtype

dtype('float64')

In [15]:
data.coords

Coordinates:
  * x        (x) int32 10 11 12
  * y        (y) int32 10 20 30 40

#### Acess specific coordinate

In [16]:
data.coords["x"]

<xarray.DataArray 'x' (x: 3)>
array([10, 11, 12])
Coordinates:
  * x        (x) int32 10 11 12

In [17]:
data.coords["y"]

<xarray.DataArray 'y' (y: 4)>
array([10, 20, 30, 40])
Coordinates:
  * y        (y) int32 10 20 30 40

#### Acess values on the coordinates

In [22]:
data.coords["x"][1]

<xarray.DataArray 'x' ()>
array(11)
Coordinates:
    x        int32 11

In [20]:
for i in range(0, len(data.coords["x"])):
    print(data.coords["x"][i])

<xarray.DataArray 'x' ()>
array(10)
Coordinates:
    x        int32 10
<xarray.DataArray 'x' ()>
array(11)
Coordinates:
    x        int32 11
<xarray.DataArray 'x' ()>
array(12)
Coordinates:
    x        int32 12


In [23]:
for i in range(0, len(data.coords["y"])):
    print(data.coords["y"][i])

<xarray.DataArray 'y' ()>
array(10)
Coordinates:
    y        int32 10
<xarray.DataArray 'y' ()>
array(20)
Coordinates:
    y        int32 20
<xarray.DataArray 'y' ()>
array(30)
Coordinates:
    y        int32 30
<xarray.DataArray 'y' ()>
array(40)
Coordinates:
    y        int32 40


#### Using pandas-like notation

In [25]:
data.x[1]

<xarray.DataArray 'x' ()>
array(11)
Coordinates:
    x        int32 11

In [26]:
data.y[1]

<xarray.DataArray 'y' ()>
array(20)
Coordinates:
    y        int32 20

In [28]:
data.x.values

array([10, 11, 12])

#### Attributes

In [29]:
data.attrs = {"author": "AR", "date": "2020-09-30"}
data.attrs["name"] = "density"
data.attrs["units"] = "g/cm^3"
data.x.attrs["units"] = "cm"
data.y.attrs["units"] = "cm"

In [30]:
data.attrs

{'author': 'AR', 'date': '2020-09-30', 'name': 'density', 'units': 'g/cm^3'}

In [31]:
data

<xarray.DataArray (y: 4, x: 3)>
array([[0.57061223, 0.87339452, 0.9745001 ],
       [0.4613398 , 0.07907363, 0.48824393],
       [0.35956502, 0.89967718, 0.873587  ],
       [0.8278617 , 0.00243419, 0.30986971]])
Coordinates:
  * x        (x) int32 10 11 12
  * y        (y) int32 10 20 30 40
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [34]:
data.x

<xarray.DataArray 'x' (x: 3)>
array([10, 11, 12])
Coordinates:
  * x        (x) int32 10 11 12
Attributes:
    units:    cm

In [37]:
data.y

<xarray.DataArray 'y' (y: 4)>
array([10, 20, 30, 40])
Coordinates:
  * y        (y) int32 10 20 30 40
Attributes:
    units:    cm

In [35]:
data["y"]

<xarray.DataArray 'y' (y: 4)>
array([10, 20, 30, 40])
Coordinates:
  * y        (y) int32 10 20 30 40
Attributes:
    units:    cm

In [36]:
data.coords["y"]

<xarray.DataArray 'y' (y: 4)>
array([10, 20, 30, 40])
Coordinates:
  * y        (y) int32 10 20 30 40
Attributes:
    units:    cm

### Subsetting arrays

#### Using the Python square brackets

In [38]:
# First row, also a DataArray
data[0,:]

<xarray.DataArray (x: 3)>
array([0.57061223, 0.87339452, 0.9745001 ])
Coordinates:
  * x        (x) int32 10 11 12
    y        int32 10
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [39]:
# last two columns
data[:, -2:]

<xarray.DataArray (y: 4, x: 2)>
array([[0.87339452, 0.9745001 ],
       [0.07907363, 0.48824393],
       [0.89967718, 0.873587  ],
       [0.00243419, 0.30986971]])
Coordinates:
  * x        (x) int32 11 12
  * y        (y) int32 10 20 30 40
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [43]:
# Can modify in-place
data[-1,-1] = 0.999999
data

<xarray.DataArray (y: 4, x: 3)>
array([[0.57061223, 0.87339452, 0.9745001 ],
       [0.4613398 , 0.07907363, 0.48824393],
       [0.35956502, 0.89967718, 0.873587  ],
       [0.8278617 , 0.00243419, 0.999999  ]])
Coordinates:
  * x        (x) int32 10 11 12
  * y        (y) int32 10 20 30 40
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [47]:
# first row, numpy array 
data.values[0,0:]

array([0.57061223, 0.87339452, 0.9745001 ])

##### DataArray.isel() selects by coordinate index (single index, list, range ) - Pandas Iloc

In [48]:
data.isel(y=1) # Second row

<xarray.DataArray (x: 3)>
array([0.4613398 , 0.07907363, 0.48824393])
Coordinates:
  * x        (x) int32 10 11 12
    y        int32 20
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [49]:
type(data.isel(y=1))

xarray.core.dataarray.DataArray

In [50]:
data.isel(y=0, x=[-2, -1]) # first row, last two columns

<xarray.DataArray (x: 2)>
array([0.87339452, 0.9745001 ])
Coordinates:
  * x        (x) int32 11 12
    y        int32 10
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [51]:
data

<xarray.DataArray (y: 4, x: 3)>
array([[0.57061223, 0.87339452, 0.9745001 ],
       [0.4613398 , 0.07907363, 0.48824393],
       [0.35956502, 0.89967718, 0.873587  ],
       [0.8278617 , 0.00243419, 0.999999  ]])
Coordinates:
  * x        (x) int32 10 11 12
  * y        (y) int32 10 20 30 40
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [52]:
data.isel(y=0, x=[-2, -1]).values

array([0.87339452, 0.9745001 ])

##### DataArray.sel() selects by coordinate value (single value, list, range ) Pandas loc

In [53]:
data.x.dtype

dtype('int32')

In [54]:
data.x.values

array([10, 11, 12])

In [55]:
data.sel(x=10)

<xarray.DataArray (y: 4)>
array([0.57061223, 0.4613398 , 0.35956502, 0.8278617 ])
Coordinates:
    x        int32 10
  * y        (y) int32 10 20 30 40
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [56]:
data.y

<xarray.DataArray 'y' (y: 4)>
array([10, 20, 30, 40])
Coordinates:
  * y        (y) int32 10 20 30 40
Attributes:
    units:    cm

In [57]:
data.sel(x=10, y=[30,40])

<xarray.DataArray (y: 2)>
array([0.35956502, 0.8278617 ])
Coordinates:
    x        int32 10
  * y        (y) int32 30 40
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

In [58]:
data.sel(x=10, y=[30,40]).values

array([0.35956502, 0.8278617 ])

In [59]:
data.sel(y=slice(15,30)) # only 15<=y<=30

<xarray.DataArray (y: 2, x: 3)>
array([[0.4613398 , 0.07907363, 0.48824393],
       [0.35956502, 0.89967718, 0.873587  ]])
Coordinates:
  * x        (x) int32 10 11 12
  * y        (y) int32 20 30
Attributes:
    author:   AR
    date:     2020-09-30
    name:     density
    units:    g/cm^3

##### DataArray.interp() interpolates by coordinate value