In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

##### Ipython Built-in magic commands

* https://ipython.readthedocs.io/en/stable/interactive/magics.html

In [8]:
%time

Wall time: 0 ns


In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 19 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 571 ms


In [9]:
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.7704526 ,  0.09705567,  0.74965203],
       [ 1.49758799,  0.9962438 ,  1.67053056]])

In [10]:
data * 10


array([[-7.70452596,  0.97055674,  7.49652033],
       [14.97587988,  9.96243804, 16.70530558]])

In [11]:
data + data

array([[-1.54090519,  0.19411135,  1.49930407],
       [ 2.99517598,  1.99248761,  3.34106112]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

* Creating ndarrays

In [14]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [16]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[1.11961459e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.20953760e-312, 5.98926353e-038]],

       [[6.40086139e+170, 2.77197992e-057],
        [4.01397421e-057, 6.40772101e+170],
        [8.82811104e+169, 1.80095743e+185]]])

In [27]:
np.random.randn(10)

array([-2.73875991,  0.89440749,  0.76004355,  0.45941747, -0.4184583 ,
        2.22309973,  0.08848987, -1.06482653,  0.9964652 , -1.54518217])

In [28]:
np.absolute(np.random.randn(10) * 100)

array([ 49.19916262,  51.44439689, 142.20158938,  34.47481654,
       112.52519678,  84.08802178,  79.49891729,  51.41122452,
       147.49275173, 178.62402951])

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [31]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3])

In [32]:
print(f"arr1: {arr1.dtype} arr2: {arr2.dtype}")

arr1: float64 arr2: int32


In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [34]:
arr.dtype

dtype('int32')

In [35]:
float_arr = arr.astype(np.float64)

In [36]:
float_arr.dtype

dtype('float64')

In [38]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [40]:
arr = arr.astype(np.int32)
arr

array([ 3, -1, -2,  0, 12, 10])

In [41]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [42]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [44]:
int_array = np.arange(10)

In [45]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [47]:
calibers.dtype

dtype('float64')

In [46]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([2614851248,        527,          0,    5713807,       1184,
                0,   16777984,        527], dtype=uint32)